// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "@prisma/config";
import "dotenv/config";
// import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url:"mysql://u258460312_kita_user:Sbva%2Ftech1@localhost:3306/u258460312_kita"
    url:"mysql://u258460312_kita_user:Sbva%2Ftech1@in-mum-web1836.main-hosting.eu:3306/u258460312_kita"
    // process.env["DATABASE_URL"],
  },
});
